remote_theme: pmarsceill/just-the-docs
color_scheme: uo
title: [ComStock EUSS Documentation]
logo: "/resources/ComStock Logo.jpg"
description: [Documentation for the End-Use Savings Shapes (EUSS) project powered by ComStock]
heading_anchors: true
search_enabled: true
url: https://comstock.github.io/
footer_content: "ComStock, Copyright (c) 2019-2022, Alliance for Sustainable Energy, LLC, and other contributors. All rights reserved."
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
